/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsIndexRouteImport } from './routes/About-Us/index'
import { Route as AboutUsContributorsRouteImport } from './routes/About-Us/contributors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/About-Us/',
  path: '/About-Us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsContributorsRoute = AboutUsContributorsRouteImport.update({
  id: '/About-Us/contributors',
  path: '/About-Us/contributors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About-Us/contributors': typeof AboutUsContributorsRoute
  '/About-Us': typeof AboutUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About-Us/contributors': typeof AboutUsContributorsRoute
  '/About-Us': typeof AboutUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About-Us/contributors': typeof AboutUsContributorsRoute
  '/About-Us/': typeof AboutUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/About-Us/contributors' | '/About-Us'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About-Us/contributors' | '/About-Us'
  id: '__root__' | '/' | '/About-Us/contributors' | '/About-Us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsContributorsRoute: typeof AboutUsContributorsRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About-Us/': {
      id: '/About-Us/'
      path: '/About-Us'
      fullPath: '/About-Us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About-Us/contributors': {
      id: '/About-Us/contributors'
      path: '/About-Us/contributors'
      fullPath: '/About-Us/contributors'
      preLoaderRoute: typeof AboutUsContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsContributorsRoute: AboutUsContributorsRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
