/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsIndexRouteImport } from './routes/About-Us/index'
import { Route as AboutUsNewAboutRouteImport } from './routes/About-Us/new-about'

const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/About-Us/',
  path: '/About-Us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsNewAboutRoute = AboutUsNewAboutRouteImport.update({
  id: '/About-Us/new-about',
  path: '/About-Us/new-about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/About-Us/new-about': typeof AboutUsNewAboutRoute
  '/About-Us': typeof AboutUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/About-Us/new-about': typeof AboutUsNewAboutRoute
  '/About-Us': typeof AboutUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/About-Us/new-about': typeof AboutUsNewAboutRoute
  '/About-Us/': typeof AboutUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Home' | '/About-Us/new-about' | '/About-Us'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Home' | '/About-Us/new-about' | '/About-Us'
  id: '__root__' | '/' | '/Home' | '/About-Us/new-about' | '/About-Us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AboutUsNewAboutRoute: typeof AboutUsNewAboutRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About-Us/': {
      id: '/About-Us/'
      path: '/About-Us'
      fullPath: '/About-Us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About-Us/new-about': {
      id: '/About-Us/new-about'
      path: '/About-Us/new-about'
      fullPath: '/About-Us/new-about'
      preLoaderRoute: typeof AboutUsNewAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AboutUsNewAboutRoute: AboutUsNewAboutRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
